[package]
name = "vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ['derive']}
rustyline = "11.0.0"
rustyline-derive = "0.8.0"
chumsky = "0.9.2"
